UI/WebStations/Models/ErrorViewModel.cs
using System;

namespace WebStations.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UI/WebStations/Models/StationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebStations.Models
{
    [Serializable]
    public class StationViewModel
    {
        [Display (Name = "Код станции")]
        public int Code { get; set; }

        [Display(Name = "Название станции")]
        public string Name { get; set; }

        [Display(Name = "Название ж/д")]
        public string NameRailway { get; set; }

        [Display(Name = "Дата обновления")]
        public DateTime DateUpdate { get; set; }
    }
}

UI/WebStations/Controllers/StationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.Threading.Tasks;
using HttpClients.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using RabbitMQ.Events;
using RawRabbit;
using RawRabbit.Context;
using WebStations.Models;

namespace WebStations.Controllers
{
    public class StationController : Controller
    {
        private const string _keyCache = "station";
        private readonly IBusClient _busClient;
        private readonly IDistributedCache _cache;
        private readonly ILogger<StationController> _logger;
        private readonly ITitleStationDb _titleStationDb;
        private bool firstLoad;

        public StationController(ILogger<StationController> logger,
            ITitleStationDb titleStationDb,
            IDistributedCache cache,
            IBusClient busClient)
        {
            _titleStationDb = titleStationDb;
            _cache = cache;
            _logger = logger;
            _busClient = busClient;
            _busClient.SubscribeAsync<UpdateInfoStationsEvent>(UpdateInfoStation);
        }

        private async Task UpdateInfoStation(UpdateInfoStationsEvent @event, IMessageContext message)
        {
            var model = await GetStations();

            await UpdateCache(model);
        }


        public async Task<IActionResult> Index()
        {
            try
            {
                var modelCache = await _cache.GetAsync(_keyCache);
                if (firstLoad && modelCache != null)
                {
                    var serialized = Encoding.UTF8.GetString(modelCache);

                    return View(JsonConvert.DeserializeObject<IEnumerable<StationViewModel>>(serialized));
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning($"{ex} Cache Redis doesn't work.");
            }

            var model = await GetStations();

            await UpdateCache(model);
            firstLoad = true;
            return View(model);
        }


        private async Task<List<StationViewModel>> GetStations()
        {
            List<StationViewModel> stations = new List<StationViewModel>();
            try
            {
                var values = await _titleStationDb.GetTitleStationAsync(10);

                if (values != null)
                {
                    foreach (var value in values)
                    {
                        stations.Add(new StationViewModel
                            {
                                Code = value.Code,
                                Name = value.Name,
                                NameRailway = value.NameRailway,
                                DateUpdate = value.DateUpdate
                            }
                        );
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning($"{ex}");
            }

            return stations;
        }

        private async Task UpdateCache(List<StationViewModel> stations)
        {
            DistributedCacheEntryOptions userExpire = new DistributedCacheEntryOptions
            {
                AbsoluteExpiration = DateTimeOffset.UtcNow.AddSeconds(3600)
            };

            var json = JsonConvert.SerializeObject(stations);
            var jsonByte = Encoding.UTF8.GetBytes(json);

            try
            {
                await _cache.SetAsync(_keyCache, jsonByte, userExpire);
            }
            catch
            {
                _logger.LogWarning("Cache Redis doesn't work.");
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

UI/WebStations/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebStations</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Station" asp-action="Index">WebStations</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

UI/WebStations/Views/Station/Index.cshtml
@model IEnumerable<WebStations.Models.StationViewModel>

@{
    ViewData["Title"] = "Home";
    //Layout = "~/Views/Home/Index.cshtml";
}

<h3>Информация по 10 последним обновленным ж/д станциям.</h3>

@{ int number = 0;}
<table class="table">
    <thead>
        <tr>
            <th>
                №
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameRailway)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateUpdate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @( ++number).
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameRailway)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateUpdate)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
    }
    </tbody>
</table>